# Python Basics: Introduction to Numpy and Datetime - Exercises

## Numpy

In [19]:
import numpy as np

### Exercise: Messing around with arrays </br>

Consider the following list:

1. Create a 5x5 numpy array with ones on the borders and zeros inside (two lines of code only)

2. Return the common values between two arrays. Search for an appropriate numpy function
to solve this task.

In [21]:
array1 =
array2 =

In [22]:
np.___(array1, array2)

#https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-18.php


array([10, 40])

3. Given two lists, append x to y using an appropriate numpy function.

In [23]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-12.php

y = [10, 20, 30]
x = [[40, 50, 60], [70, 80, 90]]

4. Perform the Cholesky decomposition of the following matrix.

In [25]:
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)

In [26]:
L = np.___.___(a)

5. Consider the following matrix.

In [33]:
a = np.array([[4, 12, -16, 5], [1, 12, 37, -53], [-16, -53, 98, 3] ,[12, 37, -53, 99]], dtype=np.int32)

array([[  4,  12, -16,   5],
       [  1,  12,  37, -53],
       [-16, -53,  98,   3],
       [ 12,  37, -53,  99]], dtype=int32)

Extract all elements below the main diagonal and return those values in an array. Experiment with two methods:

- use a classical loop through the indices
- use built-in np functions (look for clues in the internet)


In [76]:
# with a loop



[1]
[-16 -53]
[ 12  37 -53]


[1, -16, -53, 12, 37, -53]

In [60]:
# Using a build-in function



array([  1, -16, -53,  12,  37, -53], dtype=int32)

## Datetime

In [77]:
import datetime

1. Print the current time, use the built-in function of the datetime module. Print the datetype of the object.

13:40:05.146401


datetime.time

2. Transform the given current date into the format Year-written month name-day/name of the day, i.e.
2021 - March - 26/Friday

2021-February-23/Tuesday


str

3. Return the date of day 10 days ahead. Use .timedelta

2021-02-13


4. Consider the following date

In [104]:
dt = datetime.datetime.today()

print(dt)

2021-02-23 13:51:21.561035


Sometimes/Most of the time, we don't need microseconds. Use a datetime function to drop the
micro seconds. Use the built-in .replace() function

2021-02-23 13:52:19
